<template>
  <main>
    <section>
      <NebulaButton
        block
        type="primary">Primary
      </NebulaButton>
    </section>
    <section>
      <NebulaButton block>Default</NebulaButton>
    </section>
    <section>
      <NebulaButton
        block
        type="dashed">Dashed
      </NebulaButton>
    </section>
    <section>
      <NebulaButton
        block
        type="danger">danger
      </NebulaButton>
    </section>
  </main>
</template>
