<template>
  <main>
    <section>
      <NebulaButton
        icon="search"
        shape="circle"
        type="primary"/>
      <NebulaButton
        icon="search"
        type="primary">Search
      </NebulaButton>
      <NebulaButton
        icon="search"
        shape="circle"/>
      <NebulaButton icon="search">Search</NebulaButton>
    </section>
    <section>
      <NebulaButton
        icon="search"
        shape="circle"/>
      <NebulaButton icon="search">Search</NebulaButton>
      <NebulaButton
        icon="search"
        shape="circle"
        type="dashed"/>
      <NebulaButton
        icon="search"
        type="dashed">Search
      </NebulaButton>
    </section>
  </main>
</template>
